
export const options = [
    { value: 'Harry Potter', label: 'Harry Potter' },
    { value: 'Gym', label: 'Gym' },
    { value: 'SoundCloud', label: 'SoundCloud' },
    { value: 'Basketball', label: 'Basketball' },
    { value: 'Football', label: 'Football' },
    { value: 'Badminton', label: 'Badminton' },
    { value: 'Dota2', label: 'Dota2' },
    { value: 'Gaming', label: 'Gaming' },
    { value: 'Dog', label: 'Dog' },
    { value: 'Bird', label: 'Bird' },
    { value: 'VR Room', label: 'VR Room' },
    { value: 'Cosplay', label: 'Cosplay' },
    { value: 'E-Sports', label: 'E-Sports' },
    { value: 'Running', label: 'Running' },
    { value: 'Korea Dramas', label: 'Korea Dramas' },
    { value: 'Travel', label: 'Travel' },
    { value: 'Books', label: 'Books' },
    { value: 'Spotify', label: 'Spotify' },
    { value: 'Netflix', label: 'Netflix' },
    { value: 'Instagram', label: 'Instagram' },
    { value: 'Movies', label: 'Movies' },
    { value: 'J-Pop', label: 'J-Pop' },
    { value: 'Motor Sports', label: 'Motor Sports' },
    { value: 'Bodycombat', label: 'Bodycombat' },
    { value: 'Cheerleading', label: 'Cheerleading' },
    { value: 'Breaking Bad', label: 'Breaking Bad' },
    { value: 'Javascript', label: 'Javascript' },
    { value: 'React', label: 'React' },
    { value: 'NodeJs', label: 'NodeJs' },
    { value: 'Country Music', label: 'Country Music' },
    { value: 'Jogging', label: 'Jogging' },
    { value: 'Karaoke', label: 'Karaoke' },
    { value: 'Jetski', label: 'Jetski' },
    { value: 'Human Rights', label: 'Human Rights' },
    { value: 'Cafe', label: 'Cafe' },
    { value: 'Sneakers', label: 'Sneakers' },
    { value: 'Gin Tonic', label: 'Gin Tonic' },
    { value: 'Self Care', label: 'Self Care' },
    { value: 'Heavy Metal', label: 'Heavy Metal' },
    { value: 'Youtube', label: 'Youtube' },
    { value: 'Japanese Anime', label: 'Japanese Anime' },
    { value: 'Shabu', label: 'Shabu' },
    { value: 'Self Development', label: 'Self Development' },
    { value: 'Shopping', label: 'Shopping' },
    { value: 'Foodie Tour', label: 'Foodie Tour' },
]


export const optionsContact = [
    { value: 'Line', label: 'Line' },
    { value: 'Facebook', label: 'Facebook' },
    { value: 'Instragram', label: 'Instragram' },
    { value: 'Telephone', label: 'Telephone' },
    { value: 'Meet in Real Person', label: 'Meet in Real Person' },

]
